import '../models/brazilian_state.dart';

/// Constantes compartilhadas pelas validações e normalizações do pacote.
class Constants {
  Constants._();

  /// Caracteres acentuados reconhecidos por [AllValidations.removeAccents].
  static const List<String> accents = [
    'à',
    'è',
    'ì',
    'ò',
    'ù',
    'À',
    'È',
    'Ì',
    'Ò',
    'Ù',
    'á',
    'é',
    'í',
    'ó',
    'ú',
    'ý',
    'Á',
    'É',
    'Í',
    'Ó',
    'Ú',
    'Ý',
    'â',
    'ê',
    'î',
    'ô',
    'û',
    'Â',
    'Ê',
    'Î',
    'Ô',
    'Û',
    'ã',
    'ñ',
    'õ',
    'Ã',
    'Ñ',
    'Õ',
    'ä',
    'ë',
    'ï',
    'ö',
    'ü',
    'ÿ',
    'Ä',
    'Ë',
    'Ï',
    'Ö',
    'Ü',
    'Ÿ',
    'ç',
    'Ç',
    'Å',
    'å'
  ];

  /// Substituições posicionais correspondentes a [accents].
  static const List<String> noAccents = [
    'a',
    'e',
    'i',
    'o',
    'u',
    'A',
    'E',
    'I',
    'O',
    'U',
    'a',
    'e',
    'i',
    'o',
    'u',
    'y',
    'A',
    'E',
    'I',
    'O',
    'U',
    'Y',
    'a',
    'e',
    'i',
    'o',
    'u',
    'A',
    'E',
    'I',
    'O',
    'U',
    'a',
    'n',
    'o',
    'A',
    'N',
    'O',
    'a',
    'e',
    'i',
    'o',
    'u',
    'y',
    'A',
    'E',
    'I',
    'O',
    'U',
    'Y',
    'c',
    'C',
    'A',
    'a'
  ];

  /// Fonte canônica dos 67 DDDs atribuídos e suas unidades federativas.
  ///
  /// Códigos não atribuídos, como 23, 25, 26, 36, 52, 72, 76 e 78, não
  /// pertencem ao mapa.
  static const Map<String, BrazilianState> dddToState = {
    '11': BrazilianState.SP,
    '12': BrazilianState.SP,
    '13': BrazilianState.SP,
    '14': BrazilianState.SP,
    '15': BrazilianState.SP,
    '16': BrazilianState.SP,
    '17': BrazilianState.SP,
    '18': BrazilianState.SP,
    '19': BrazilianState.SP,
    '21': BrazilianState.RJ,
    '22': BrazilianState.RJ,
    '24': BrazilianState.RJ,
    '27': BrazilianState.ES,
    '28': BrazilianState.ES,
    '31': BrazilianState.MG,
    '32': BrazilianState.MG,
    '33': BrazilianState.MG,
    '34': BrazilianState.MG,
    '35': BrazilianState.MG,
    '37': BrazilianState.MG,
    '38': BrazilianState.MG,
    '41': BrazilianState.PR,
    '42': BrazilianState.PR,
    '43': BrazilianState.PR,
    '44': BrazilianState.PR,
    '45': BrazilianState.PR,
    '46': BrazilianState.PR,
    '47': BrazilianState.SC,
    '48': BrazilianState.SC,
    '49': BrazilianState.SC,
    '51': BrazilianState.RS,
    '53': BrazilianState.RS,
    '54': BrazilianState.RS,
    '55': BrazilianState.RS,
    '61': BrazilianState.DF,
    '62': BrazilianState.GO,
    '63': BrazilianState.TO,
    '64': BrazilianState.GO,
    '65': BrazilianState.MT,
    '66': BrazilianState.MT,
    '67': BrazilianState.MS,
    '68': BrazilianState.AC,
    '69': BrazilianState.RO,
    '71': BrazilianState.BA,
    '73': BrazilianState.BA,
    '74': BrazilianState.BA,
    '75': BrazilianState.BA,
    '77': BrazilianState.BA,
    '79': BrazilianState.SE,
    '81': BrazilianState.PE,
    '82': BrazilianState.AL,
    '83': BrazilianState.PB,
    '84': BrazilianState.RN,
    '85': BrazilianState.CE,
    '86': BrazilianState.PI,
    '87': BrazilianState.PE,
    '88': BrazilianState.CE,
    '89': BrazilianState.PI,
    '91': BrazilianState.PA,
    '92': BrazilianState.AM,
    '93': BrazilianState.PA,
    '94': BrazilianState.PA,
    '95': BrazilianState.RR,
    '96': BrazilianState.AP,
    '97': BrazilianState.AM,
    '98': BrazilianState.MA,
    '99': BrazilianState.MA,
  };

  /// Lista somente leitura derivada da fonte canônica [dddToState].
  static final List<String> ddds = List.unmodifiable(dddToState.keys);
}
